# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi/api.proto\x12\x03\x61pi\"\r\n\x0bPageRequest\"\x1d\n\x0cPageResponse\x12\r\n\x05title\x18\x01 \x01(\t27\n\x03\x41PI\x12\x30\n\x07GetPage\x12\x10.api.PageRequest\x1a\x11.api.PageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAGEREQUEST']._serialized_start=22
  _globals['_PAGEREQUEST']._serialized_end=35
  _globals['_PAGERESPONSE']._serialized_start=37
  _globals['_PAGERESPONSE']._serialized_end=66
  _globals['_API']._serialized_start=68
  _globals['_API']._serialized_end=123
# @@protoc_insertion_point(module_scope)
