# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import book_pb2 as api_dot_book__pb2


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/BookService/GetBook',
                request_serializer=api_dot_book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=api_dot_book__pb2.Book.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/BookService/ListBooks',
                request_serializer=api_dot_book__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=api_dot_book__pb2.ListBooksResponse.FromString,
                )
        self.CreateBook = channel.unary_unary(
                '/BookService/CreateBook',
                request_serializer=api_dot_book__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=api_dot_book__pb2.Book.FromString,
                )
        self.UpdateBook = channel.unary_unary(
                '/BookService/UpdateBook',
                request_serializer=api_dot_book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=api_dot_book__pb2.Book.FromString,
                )
        self.DeleteBook = channel.unary_unary(
                '/BookService/DeleteBook',
                request_serializer=api_dot_book__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=api_dot_book__pb2.DeleteBookResponse.FromString,
                )


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=api_dot_book__pb2.GetBookRequest.FromString,
                    response_serializer=api_dot_book__pb2.Book.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=api_dot_book__pb2.ListBooksRequest.FromString,
                    response_serializer=api_dot_book__pb2.ListBooksResponse.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=api_dot_book__pb2.CreateBookRequest.FromString,
                    response_serializer=api_dot_book__pb2.Book.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=api_dot_book__pb2.UpdateBookRequest.FromString,
                    response_serializer=api_dot_book__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=api_dot_book__pb2.DeleteBookRequest.FromString,
                    response_serializer=api_dot_book__pb2.DeleteBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/GetBook',
            api_dot_book__pb2.GetBookRequest.SerializeToString,
            api_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/ListBooks',
            api_dot_book__pb2.ListBooksRequest.SerializeToString,
            api_dot_book__pb2.ListBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/CreateBook',
            api_dot_book__pb2.CreateBookRequest.SerializeToString,
            api_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/UpdateBook',
            api_dot_book__pb2.UpdateBookRequest.SerializeToString,
            api_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/DeleteBook',
            api_dot_book__pb2.DeleteBookRequest.SerializeToString,
            api_dot_book__pb2.DeleteBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
