# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pi/book.proto\"0\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x12\n\x10ListBooksRequest\")\n\x11ListBooksResponse\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book\"(\n\x11\x43reateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"(\n\x11UpdateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"\x1f\n\x11\x44\x65leteBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x14\n\x12\x44\x65leteBookResponse2\xf7\x01\n\x0b\x42ookService\x12#\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x05.Book\"\x00\x12\x34\n\tListBooks\x12\x11.ListBooksRequest\x1a\x12.ListBooksResponse\"\x00\x12)\n\nCreateBook\x12\x12.CreateBookRequest\x1a\x05.Book\"\x00\x12)\n\nUpdateBook\x12\x12.UpdateBookRequest\x1a\x05.Book\"\x00\x12\x37\n\nDeleteBook\x12\x12.DeleteBookRequest\x1a\x13.DeleteBookResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=18
  _globals['_BOOK']._serialized_end=66
  _globals['_GETBOOKREQUEST']._serialized_start=68
  _globals['_GETBOOKREQUEST']._serialized_end=96
  _globals['_LISTBOOKSREQUEST']._serialized_start=98
  _globals['_LISTBOOKSREQUEST']._serialized_end=116
  _globals['_LISTBOOKSRESPONSE']._serialized_start=118
  _globals['_LISTBOOKSRESPONSE']._serialized_end=159
  _globals['_CREATEBOOKREQUEST']._serialized_start=161
  _globals['_CREATEBOOKREQUEST']._serialized_end=201
  _globals['_UPDATEBOOKREQUEST']._serialized_start=203
  _globals['_UPDATEBOOKREQUEST']._serialized_end=243
  _globals['_DELETEBOOKREQUEST']._serialized_start=245
  _globals['_DELETEBOOKREQUEST']._serialized_end=276
  _globals['_DELETEBOOKRESPONSE']._serialized_start=278
  _globals['_DELETEBOOKRESPONSE']._serialized_end=298
  _globals['_BOOKSERVICE']._serialized_start=301
  _globals['_BOOKSERVICE']._serialized_end=548
# @@protoc_insertion_point(module_scope)
